AllCops:
  NewCops: enable

Metrics/MethodLength:
  Max: 20

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/**/*'

Metrics/BlockLength:
  Exclude:
    - 'tasks/**/*'

Style/Documentation:
  Enabled: false
