default: &default
  adapter: postgresql
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: repo_test_development

development:
  <<: *default
  database: repo_test_test
